// eslint@^9: neostandard, eslint-plugin-import, eslint-plugin-react y
// eslint-plugin-jsx-a11y aún no soportan ESLint 10 — quitar el pin cuando lo hagan.
export const depsByFramework = {
  nextjs: [
    "eslint@^9",
    "@eslint/compat",
    "@next/eslint-plugin-next",
    "eslint-config-next",
    "eslint-config-prettier",
    "eslint-plugin-import",
    "eslint-plugin-jsx-a11y",
    "eslint-plugin-prettier",
    "eslint-plugin-react",
    "eslint-plugin-react-compiler",
    "eslint-plugin-react-hooks",
    "prettier",
    "prettier-plugin-tailwindcss",
    "typescript",
    "typescript-eslint",
    "globals",
  ],
  vite: [
    "eslint@^9",
    "@eslint/compat",
    "eslint-config-prettier",
    "eslint-plugin-import",
    "eslint-plugin-jsx-a11y",
    "eslint-plugin-prettier",
    "eslint-plugin-react",
    "eslint-plugin-react-hooks",
    "prettier",
    "prettier-plugin-tailwindcss",
    "typescript",
    "typescript-eslint",
    "globals",
  ],
  "backend-ts": [
    "eslint@^9",
    "@eslint/compat",
    "eslint-config-prettier",
    "eslint-plugin-import",
    "eslint-plugin-prettier",
    "neostandard",
    "prettier",
    "typescript",
  ],
};
